import type { CardDef } from '../engine/types';

// The PLAN.md section 4 exemplar cards, verbatim. Placeholders, NOT balanced;
// the pool grows to targets (~15/color + ~10 colorless) in Phase 5 and gets
// tuned by the sim harness, never by intuition.

const ALL_SLOTS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
// Premium artifacts install high only (2026-07-13: colorless was bought too
// often; the strongest pieces now live where fires are rare and echoes carry).
const HIGH_SLOTS = [7, 8, 9, 10, 11, 12];

export const RED_CARDS: CardDef[] = [
  {
    id: 'cinder-bolt',
    name: 'Cinder Bolt',
    icon: 'Ability_Mage_FireStarter.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 5],
    active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'stoke-the-forge',
    name: 'Stoke the Forge',
    icon: 'Achievement_Zone_Ironforge.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [4, 6],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'blood-for-power',
    name: 'Blood for Power',
    icon: 'ability_deathwing_bloodcorruption_earth.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 7,
    legalSlots: [5, 6],
    active: [
      { kind: 'damage', amount: 2, target: 'roller' }, // self-risk: your own turn, you are the roller
      { kind: 'gainPoints', amount: 3 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'meteor-call',
    name: 'Meteor Call',
    icon: 'Spell_Mage_Meteor.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [10, 11, 12],
    active: [
      { kind: 'damage', amount: 4, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  // --- P5 batch ---
  {
    id: 'ember-jab',
    name: 'Ember',
    icon: 'INV_Elemental_Mote_Fire01.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [4],
    active: [
      { kind: 'damage', amount: 1, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'kindling-rage',
    name: 'Kindling Rage',
    icon: 'Spell_Nature_ShamanRage.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [5, 6],
    active: [
      { kind: 'damage', amount: 1, target: 'chooseOpponent' },
      {
        kind: 'conditional',
        when: { sumAtLeast: 9 },
        then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }],
      },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'bellows',
    name: 'Bellows',
    icon: 'INV_Archaeology_Orcclans_Bellow.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 10 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'blood-tithe',
    name: 'Blood Tithe',
    icon: 'Ability_IronMaidens_CorruptedBlood.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 5],
    active: [
      { kind: 'damage', amount: 1, target: 'roller' },
      { kind: 'gainMoney', amount: 3 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'cauterize',
    name: 'Cauterize',
    icon: 'Ability_DemonHunter_ChaoticImprint_Fire.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3, // tuning 2026-07-13: -18 delta; the clutch heal for the blood color
    legalSlots: [4, 6],
    active: [
      { kind: 'heal', amount: 2 },
      { kind: 'conditional', when: { hpAtOrBelow: 10 }, then: [{ kind: 'heal', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'powder-keg',
    name: 'Powder Keg',
    icon: 'INV_Engineering_Gunpack.PNG',
    color: 'red',
    rarity: 'common',
    cost: 5,
    legalSlots: [4, 5, 6],
    active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'wildfire',
    name: 'Wildfire',
    icon: 'Ability_Racial_FireResist.PNG',
    color: 'red',
    rarity: 'common',
    cost: 5,
    legalSlots: [9, 10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'flare-up',
    name: 'Flare-Up',
    icon: 'Spell_Fire_Flare.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'martyrs-flame',
    name: "Martyr's Flame",
    icon: 'Spell_Nature_UnleashedRage.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 7,
    legalSlots: [4, 5],
    active: [
      { kind: 'damage', amount: 2, target: 'roller' },
      { kind: 'damage', amount: 3, target: 'chooseOpponent' },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'inferno-engine',
    name: 'Inferno Engine',
    icon: 'ABILITY_WARLOCK_INFERNO.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [11, 12],
    active: [{ kind: 'damage', amount: 5, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }], // tuning 2026-07-13 round 2
  },
  {
    id: 'cinder-crown',
    name: 'Cinder Crown',
    icon: 'INV_Crown_13.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8, // tuning 2026-07-13: -13 delta at cost 9
    legalSlots: [10, 11],
    active: [
      { kind: 'damage', amount: 3, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 2 },
      // tuning 2026-07-13 round 2: was sumAtLeast 11, which can never pay in
      // slot 10 (a slot-10 hit means the sum was exactly 10) - a dead bonus.
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }],
  },
  // --- 2026-07-13 high-band batch (Jake: 5 new 7-12 cards per color) ---
  {
    id: 'ember-storm',
    name: 'Ember Storm',
    icon: 'ability_warlock_burningembers.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [9, 10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'conditional', when: { sumAtLeast: 10 }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'backdraft',
    name: 'Backdraft',
    icon: 'Ability_Warlock_Backdraft.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'slow-burn',
    name: 'Slow Burn',
    icon: 'INV_Jewelcrafting_Pyrestone_01.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [9],
    // Echo-centric: cover it and every heard 9 singes the roller.
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }],
  },
  {
    id: 'eruption',
    name: 'Eruption',
    icon: 'Ability_Rhyolith_Volcano.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 9,
    legalSlots: [11, 12],
    active: [
      { kind: 'damage', amount: 4, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }],
  },
  {
    id: 'pyre-of-glory',
    name: 'Pyre of Glory',
    icon: 'INV_Inscription_Tarot_VolcanoCard.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [10, 11],
    active: [
      { kind: 'damage', amount: 1, target: 'roller' },
      { kind: 'gainPoints', amount: 4 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
];

export const BLUE_CARDS: CardDef[] = [
  {
    id: 'ripple',
    name: 'Ripple',
    icon: 'Ability_Shaman_FortifyingWaters.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [2, 3],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'second-glance',
    name: 'Second Glance',
    icon: 'Sha_Ability_Rogue_BloodyEye.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainToken', token: 'reroll', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'chronoloop',
    name: 'Chronoloop',
    icon: 'Spell_Mage_AlterTime_Active.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 7,
    legalSlots: [1, 3],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { allocatedIndividually: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'tide-engine',
    name: 'Tidal Totem',
    icon: 'Ability_Shaman_HealingTide.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 2, 3],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- P5 batch ---
  {
    id: 'tide-pool',
    name: 'Tide Pool',
    icon: 'INV_Misc_Food_Legion_GooAmberPurple_pool.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [
      { kind: 'gainMoney', amount: 2 }, // tuning 2026-07-13: was 1 (-11 delta)
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'undertow',
    name: 'Undertow',
    icon: 'Ability_ShaWaterElemental_Swirl.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainMoney', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'driftwood',
    name: 'Driftwood',
    icon: 'INV_Archaeology_80_Witch_EtchedDrustBone.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [3],
    active: [{ kind: 'gainPoints', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'spyglass',
    name: 'Spyglass',
    icon: 'INV_Misc_Spyglass_02.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3, // tuning 2026-07-13: -10 delta at both counts
    legalSlots: [1, 2],
    active: [{ kind: 'refreshShop' }, { kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'current-reader',
    name: 'Flowing Current',
    icon: 'Spell_Mage_IceFlows.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 2, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mooring-line',
    name: 'Icy Breeze',
    icon: 'Spell_Frost_ArcticWinds.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
    ],
    // tuning 2026-07-13: slot-7 echoes hear every sum now; a point echo is the payoff
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'seventh-wave',
    name: 'Seventh Wave',
    icon: 'Spell_AnimaArdenweald_Wave.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4, // tuning 2026-07-13: worst high card at 2p (40% buyer win)
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'ebb-gate',
    name: 'Ebb Gate',
    icon: 'Spell_Shaman_HighTide.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 7],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tempest-loom',
    name: 'Arcane Tempest',
    icon: 'spell_Mage_NetherTempest.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainToken', token: 'reroll', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tidal-crown',
    name: 'Tidal Crown',
    icon: 'Item_icecrownringD.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 9,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 3 },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'mirror-bay',
    name: 'Mirror Bay',
    icon: 'Trade_Archaeology_HighborneSoulMirror.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 7,
    legalSlots: [2, 3],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'refreshShop' },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: blue's sum territory is the 7 ---
  {
    id: 'lucky-seven',
    name: 'Lucky Seven',
    icon: 'INV_Misc_Dice_01.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainToken', token: 'reroll', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'riptide',
    name: 'Riptide',
    icon: 'Spell_Nature_Riptide.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'seventh-sense',
    name: 'Seventh Sense',
    icon: 'INV_Inscription_TarotIllusion.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 5,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'crest-of-the-wave',
    name: 'Crest of the Wave',
    icon: 'Spell_Shaman_TidalWaves.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'maelstrom',
    name: 'Maelstrom',
    icon: 'Spell_Shaman_MaelstromWeapon.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 9,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
];

// Colorless = MARKET ARTIFACTS (2026-07-13): a shared static shop all players
// compete over. Stronger than color cards, priced 8-14, any slot at purchase.
export const COLORLESS_CARDS: CardDef[] = [
  {
    id: 'coin-sprite',
    name: 'Coin Sprite',
    icon: 'INV_Misc_AzsharaCoin2.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13: -9 delta at 4p
  },
  {
    id: 'lucky-charm',
    name: 'Lucky Charm',
    icon: 'INV_Jewelry_Necklace_03.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 10, // tuning 2026-07-13: +6 delta at both counts
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'prism-core',
    name: 'Prism Core',
    icon: 'INV_Enchant_ShardPrismaticLarge.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 12, // tuning 2026-07-13: +16 delta at 4p, the strongest card in the pool
    legalSlots: HIGH_SLOTS,
    active: [{ kind: 'gainPoints', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tin-totem',
    name: 'Steel Totem',
    icon: 'Spell_Nature_WrathofAir_Totem.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      // tuning 2026-07-13: threshold 12 -> 15 (HP pools are 22/18/16 by player count)
      { kind: 'conditional', when: { hpAtOrBelow: 15 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'barter-stone',
    name: 'Barter Stone',
    icon: 'INV_Misc_Archstone_01.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7, // tuning 2026-07-13
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainMoney', amount: 4 }, { kind: 'refreshShop' }], // tuning round 2
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'keepsake',
    name: 'Keepsake',
    icon: 'INV_Ring_Bastion_01_Silver.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainPoints', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'medic-kit',
    name: 'Medic Kit',
    icon: 'INV_FIRST_AID_70_MedicalKit.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'heal', amount: 3 }, // tuning 2026-07-13
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'hoard-charm',
    name: 'Hoard Charm',
    icon: 'INV_Archaeology_70_Highborne_InertLeystoneCharm.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 8, // tuning 2026-07-13
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'gainMoney', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-idol',
    name: 'Golden Idol',
    icon: 'INV_QirajIdol_Sun.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 11,
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'phoenix-plate',
    name: 'Phoenix Plate',
    icon: 'INV_CHEST_CLOTH_68.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 12,
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'heal', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { hpAtOrBelow: 10 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
];

// BLACK "Gravebound": slots {1,6} + doubles-only sums {2,12}. Doubles payoffs
// and echo-stack (graveyard) synergy. Echo flavor: points from the grave.
export const BLACK_CARDS: CardDef[] = [
  {
    id: 'grave-tithe',
    name: 'Grave Tithe',
    icon: 'Ability_Argus_DeathFog.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 2 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'bone-dice',
    name: 'Bone Dice',
    icon: 'Ability_Rogue_RolltheBones.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'shallow-grave',
    name: 'Shallow Grave',
    icon: 'Achievement_BG_Xkills_AVgraveyard.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 3 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mourners-coin',
    name: "Mourner's Coin",
    icon: 'INV_Misc_AzsharaCoin.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      // tuning 2026-07-13: doubles bonus 2 -> 3
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainMoney', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'six-feet-under',
    name: 'Six Feet Under',
    icon: 'Ability_FiegnDead.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      // tuning 2026-07-13: threshold 5 -> 4
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'snake-eyes',
    name: 'Snake Eyes',
    icon: 'INV_GiantSnake_Black.PNG',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false }, // the true snake eyes: sum 2 = double 1s
        then: [
          { kind: 'gainPoints', amount: 4 },
          { kind: 'gainMoney', amount: 1 },
        ],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'pallbearer',
    name: 'Pallbearer',
    icon: 'INV_Axe_2H_UndeadGuitar_C_01.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [6],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'echo-chamber',
    name: 'Echo Chamber',
    icon: 'Achievement_Scenario_TombofForgottenKings.PNG',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'death-rattle',
    name: 'Death Rattle',
    icon: 'Spell_Shadow_RaiseDead.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false },
        then: [
          { kind: 'gainMoney', amount: 2 },
          { kind: 'gainPoints', amount: 1 },
        ],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'boxcars',
    name: "Death's Advance",
    icon: 'INV_SkeletalWarhorse_01_Brown.PNG',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 4 }, // tuning 2026-07-13: sum 12 is 1/36; jackpot or nothing
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'grave-engine',
    name: 'Grave Engine',
    icon: 'INV_Engineering_90_GhostTrap.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 3 }, then: [{ kind: 'gainPoints', amount: 1 }] },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'double-down',
    name: 'Double Down',
    icon: 'Ability_DemonHunter_DoubleJump.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 7,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      // tuning 2026-07-13: doubles jackpot 3 -> 4
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 4 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'midnight-jackpot',
    name: 'Midnight Jackpot',
    icon: 'ability_rogue_dirtydeeds.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 9,
    legalSlots: [2, 12],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false }, // only the true doubles sums pay out
        then: [{ kind: 'gainPoints', amount: 5 }],
      },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'crypt-hoard',
    name: 'Crypt Hoard',
    icon: 'Battleground_Strongbox_Gold_Horde.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'legion-of-echoes',
    name: 'Legion of Echoes',
    icon: 'Ability_Shaman_EchooftheElements.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 9,
    legalSlots: [6, 12],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: black's sum territory is the 12 ---
  {
    id: 'graveyard-shift',
    name: 'Graveyard Shift',
    icon: 'INV_GraveGolemPet.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { echoStackAtLeast: 3 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'last-rites',
    name: 'Last Rites',
    icon: 'Spell_Shadow_DarkRitual.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { echoStackAtLeast: 2 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'tombstone',
    name: 'Tombstone',
    icon: '70_inscription_vantus_rune_tomb.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [12],
    active: [{ kind: 'gainMoney', amount: 4 }],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'dead-mans-hand',
    name: "Dead Man's Hand",
    icon: 'INV_Inscription_TarotDeath.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 4 },
      { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'ossuary',
    name: 'Ossuary',
    icon: 'Achievement_Dungeon_TombOfSargeras.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 7,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
];

// GREEN "Wildgrove": odd slots {1,3,5} + odd sums {3,5,9}. Odd-dice parity
// payoffs and shop economy (discounts, refreshes). Echo flavor: money trickle.
export const GREEN_CARDS: CardDef[] = [
  {
    id: 'clover',
    name: 'Seedling',
    icon: 'Inv_Farm_PumpkinSeed_Green.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      // tuning 2026-07-13: odd-parity bonus 1 -> 2 (-8 delta)
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'odd-jobs',
    name: 'Odd Jobs',
    icon: 'INV_Engineering_90_WormholeGenerator.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'thrift-sprout',
    name: 'Thrift Sprout',
    icon: 'ABILITY_DRUID_NOURISH.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'market-vine',
    name: 'Market Vine',
    icon: 'INV_Misc_Herb_NightmareVine_Stem.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 5],
    // tuning 2026-07-13: had no direct gain at all
    active: [{ kind: 'refreshShop' }, { kind: 'discount', amount: 1 }, { kind: 'gainMoney', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'crooked-scales',
    name: 'Crooked Scales',
    icon: 'INV_Misc_ElvenCoins.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [3, 5],
    active: [
      { kind: 'gainMoney', amount: 2 }, // tuning 2026-07-13: base 1 -> 2 (-8.5 delta)
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'seedling-swap',
    name: 'Sapling Swap',
    icon: 'SPELL_NATURE_HEALINGTOUCH.PNG',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 3, 5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'ninth-harvest',
    name: 'Ninth Harvest',
    icon: 'Spell_Warlock_HarvestofLife.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13: slot-9 echoes hear every sum now
  },
  {
    id: 'bargain-bloom',
    name: 'Bargain Bloom',
    icon: 'Achievement_Dungeon_Everbloom.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [{ kind: 'discount', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'wild-growth',
    name: 'Wild Mushroom',
    icon: 'Druid_Ability_Wildmushroom_b.PNG',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13
  },
  {
    id: 'odd-omen',
    name: 'Odds and Ends',
    icon: 'Ability_Druid_Replenish.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [5],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'verdant-engine',
    name: 'Verdant Engine',
    icon: 'INV_Inscription_Pigment_Verdant.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 3, 5],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'harvest-moon',
    name: 'Harvest Moon',
    icon: 'artifactability_BalanceDruid_Fullmoon.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8, // tuning 2026-07-13
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-trellis',
    name: 'Golden Trellis',
    icon: 'INV_Misc_Herb_Nightmarevine.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 7,
    legalSlots: [3, 5],
    active: [
      { kind: 'refreshShop' },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'thicket-of-threes',
    name: 'Thicket of Threes',
    icon: 'Ability_Druid_ManaTree.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 7,
    legalSlots: [3],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'everbloom',
    name: 'Everbloom',
    icon: 'INV_Misc_Herb_Arrowbloom.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [5, 9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: green's sum territory is the 9. NOTE:
  // bothDiceOdd can never be true on a summed 9 (odd sums split odd+even),
  // so these stay parity-free on purpose - the cinder-crown lesson.
  {
    id: 'ninth-life',
    name: 'Ninth Life',
    icon: 'Ability_Druid_TreeofLife.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'moonlit-market',
    name: 'Moonlit Market',
    icon: 'Ability_Druid_ImprovedMoonkinForm.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'refreshShop' },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'autumn-tithe',
    name: 'Autumn Tithe',
    icon: 'Ability_Ardenweald_Paladin_Autumn.PNG',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'elder-grove',
    name: 'Elder Grove',
    icon: 'Ability_Druid_ProtectionOfTheGrove.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'season-of-plenty',
    name: 'Season of Plenty',
    icon: 'INV_Holiday_Thanksgiving_Cornucopia.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 9,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
];

// YELLOW "Gildmint": slots {2,4} + the unclaimed middle sums {6,8}. Raw coin
// generation plus trades that flip coins into points or HP. Echo: money.
export const YELLOW_CARDS: CardDef[] = [
  {
    id: 'penny-mint',
    name: 'Penny Mint',
    icon: 'INV_Misc_Coin_05.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [2],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'coin-press',
    name: 'Coin Press',
    icon: 'Achievement_Dungeon_CoinOperatedCrowdPummeler.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 4],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'money-changer',
    name: 'Money Changer',
    icon: 'Ability_Racial_TimeIsMoney.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3, // tuning 2026-07-13: -10 delta at cost 4
    legalSlots: [4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-goose',
    name: 'Rocket Chicken',
    icon: 'INV_Misc_EngGizmos_RocketChicken.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [6],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tollbooth',
    name: 'Tollbooth',
    icon: 'INV_Misc_LuckyMoneyEnvelope.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13: the toll pays on others' turns
  },
  {
    id: 'exchange-window',
    name: 'Golden Salve',
    icon: 'Trade_Alchemy_PotionA4.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [4, 6],
    // tuning 2026-07-13: pure trade with no base gain ran -12
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'piggy-bank',
    name: 'Piggy Bank',
    icon: 'INV_BabyPig.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 1, then: [{ kind: 'heal', amount: 2 }] }, // tuning 2026-07-13
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'gilded-scale',
    name: 'Gilded Harp',
    icon: 'Inv_Misc_Trinket_GoldenHarp.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mint-condition',
    name: 'Mint Condition',
    icon: 'INV_Misc_Coin_01.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [2, 4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'eight-ball',
    name: 'Golden Nugget',
    icon: 'INV_Misc_Gem_GoldenDraenite_01.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 4, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'midas-touch',
    name: 'Midas Touch',
    icon: 'INV_MawGuardHandMountGold.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [6, 8],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'royal-mint',
    name: 'Royal Mint',
    icon: 'Achievement_ChallengeMode_Auchindoun_Gold.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 9,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'alchemists-ledger',
    name: "Alchemist's Ledger",
    icon: 'INV_Misc_Profession_Book_Alchemy.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [2, 4],
    active: [{ kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 2 }] }],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'fort-knox',
    name: 'Fort Knox',
    icon: 'ACHIEVEMENT_GUILDPERK_MOBILEBANKING.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [4, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'trade', pay: 5, then: [{ kind: 'gainPoints', amount: 4 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'counting-house',
    name: 'Counting House',
    icon: 'Ability_Racial_PackHobgoblin.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 2, then: [{ kind: 'heal', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: yellow's sum territory is the 8 ---
  {
    id: 'loose-change',
    name: 'Loose Change',
    icon: 'Archaeology_5_0_MoguCoin.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'bullion',
    name: 'Bullion',
    icon: 'INV_Ingot_03.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'treasure-map',
    name: 'Treasure Map',
    icon: 'Icon_TreasureMap.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'the-vault',
    name: 'The Vault',
    icon: 'achievement_dungeon_VaultoftheWardens.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'dragons-hoard',
    name: "Dragon's Hoard",
    icon: 'inv_misc_treasurechest01b.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 5 }],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
];

export function pools() {
  return {
    red: RED_CARDS,
    blue: BLUE_CARDS,
    black: BLACK_CARDS,
    green: GREEN_CARDS,
    yellow: YELLOW_CARDS,
    colorless: COLORLESS_CARDS,
  };
}
