import type { CardDef } from '../engine/types';

// The PLAN.md section 4 exemplar cards, verbatim. Placeholders, NOT balanced;
// the pool grows to targets (~15/color + ~10 colorless) in Phase 5 and gets
// tuned by the sim harness, never by intuition.

const ALL_SLOTS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export const RED_CARDS: CardDef[] = [
  {
    id: 'cinder-bolt',
    name: 'Cinder Bolt',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 5],
    active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'stoke-the-forge',
    name: 'Stoke the Forge',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [4, 6],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'blood-for-power',
    name: 'Blood for Power',
    color: 'red',
    rarity: 'rare',
    cost: 7,
    legalSlots: [5, 6],
    active: [
      { kind: 'damage', amount: 2, target: 'roller' }, // self-risk: your own turn, you are the roller
      { kind: 'gainPoints', amount: 3 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'meteor-call',
    name: 'Meteor Call',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [10, 11, 12],
    active: [
      { kind: 'damage', amount: 4, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  // --- P5 batch ---
  {
    id: 'ember-jab',
    name: 'Ember Jab',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [4],
    active: [
      { kind: 'damage', amount: 1, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'kindling-rage',
    name: 'Kindling Rage',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [5, 6],
    active: [
      { kind: 'damage', amount: 1, target: 'chooseOpponent' },
      {
        kind: 'conditional',
        when: { sumAtLeast: 9 },
        then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }],
      },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'bellows',
    name: 'Bellows',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 10 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'blood-tithe',
    name: 'Blood Tithe',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 5],
    active: [
      { kind: 'damage', amount: 1, target: 'roller' },
      { kind: 'gainMoney', amount: 3 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'cauterize',
    name: 'Cauterize',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 6],
    active: [{ kind: 'heal', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'powder-keg',
    name: 'Powder Keg',
    color: 'red',
    rarity: 'common',
    cost: 5,
    legalSlots: [4, 5, 6],
    active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'wildfire',
    name: 'Wildfire',
    color: 'red',
    rarity: 'common',
    cost: 5,
    legalSlots: [9, 10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'flare-up',
    name: 'Flare-Up',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'martyrs-flame',
    name: "Martyr's Flame",
    color: 'red',
    rarity: 'rare',
    cost: 7,
    legalSlots: [4, 5],
    active: [
      { kind: 'damage', amount: 2, target: 'roller' },
      { kind: 'damage', amount: 3, target: 'chooseOpponent' },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'inferno-engine',
    name: 'Inferno Engine',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [11, 12],
    active: [{ kind: 'damage', amount: 5, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'cinder-crown',
    name: 'Cinder Crown',
    color: 'red',
    rarity: 'rare',
    cost: 9,
    legalSlots: [10, 11],
    active: [
      { kind: 'damage', amount: 3, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 11 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
];

export const BLUE_CARDS: CardDef[] = [
  {
    id: 'ripple',
    name: 'Ripple',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [2, 3],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'second-glance',
    name: 'Second Glance',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainToken', token: 'reroll', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'chronoloop',
    name: 'Chronoloop',
    color: 'blue',
    rarity: 'rare',
    cost: 7,
    legalSlots: [1, 3],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { allocatedIndividually: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'tide-engine',
    name: 'Tide Engine',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 2, 3],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- P5 batch ---
  {
    id: 'tide-pool',
    name: 'Tide Pool',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'undertow',
    name: 'Undertow',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainMoney', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'driftwood',
    name: 'Driftwood',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [3],
    active: [{ kind: 'gainPoints', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'spyglass',
    name: 'Spyglass',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [{ kind: 'refreshShop' }, { kind: 'gainMoney', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'current-reader',
    name: 'Current Reader',
    color: 'blue',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 2, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mooring-line',
    name: 'Mooring Line',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'seventh-wave',
    name: 'Seventh Wave',
    color: 'blue',
    rarity: 'common',
    cost: 5,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'ebb-gate',
    name: 'Ebb Gate',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 7],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tempest-loom',
    name: 'Tempest Loom',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainToken', token: 'reroll', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tidal-crown',
    name: 'Tidal Crown',
    color: 'blue',
    rarity: 'rare',
    cost: 9,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 3 },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'mirror-bay',
    name: 'Mirror Bay',
    color: 'blue',
    rarity: 'rare',
    cost: 7,
    legalSlots: [2, 3],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'refreshShop' },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
];

// Colorless = MARKET ARTIFACTS (2026-07-13): a shared static shop all players
// compete over. Stronger than color cards, priced 8-14, any slot at purchase.
export const COLORLESS_CARDS: CardDef[] = [
  {
    id: 'coin-sprite',
    name: 'Coin Sprite',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'lucky-charm',
    name: 'Lucky Charm',
    color: 'colorless',
    rarity: 'common',
    cost: 9,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'prism-core',
    name: 'Prism Core',
    color: 'colorless',
    rarity: 'rare',
    cost: 11,
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainPoints', amount: 3 }],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'tin-totem',
    name: 'Tin Totem',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { hpAtOrBelow: 12 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'barter-stone',
    name: 'Barter Stone',
    color: 'colorless',
    rarity: 'common',
    cost: 8,
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainMoney', amount: 3 }, { kind: 'refreshShop' }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'keepsake',
    name: 'Keepsake',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainPoints', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'medic-kit',
    name: 'Medic Kit',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'heal', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'hoard-charm',
    name: 'Hoard Charm',
    color: 'colorless',
    rarity: 'common',
    cost: 9,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'gainMoney', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-idol',
    name: 'Golden Idol',
    color: 'colorless',
    rarity: 'rare',
    cost: 11,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'phoenix-plate',
    name: 'Phoenix Plate',
    color: 'colorless',
    rarity: 'rare',
    cost: 12,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'heal', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { hpAtOrBelow: 10 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
];

// BLACK "Gravebound": slots {1,6} + doubles-only sums {2,12}. Doubles payoffs
// and echo-stack (graveyard) synergy. Echo flavor: points from the grave.
export const BLACK_CARDS: CardDef[] = [
  {
    id: 'grave-tithe',
    name: 'Grave Tithe',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 2 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'bone-dice',
    name: 'Bone Dice',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'shallow-grave',
    name: 'Shallow Grave',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 3 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mourners-coin',
    name: "Mourner's Coin",
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'six-feet-under',
    name: 'Six Feet Under',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'snake-eyes',
    name: 'Snake Eyes',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false }, // the true snake eyes: sum 2 = double 1s
        then: [
          { kind: 'gainPoints', amount: 4 },
          { kind: 'gainMoney', amount: 1 },
        ],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'pallbearer',
    name: 'Pallbearer',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [6],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'echo-chamber',
    name: 'Echo Chamber',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'death-rattle',
    name: 'Death Rattle',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false },
        then: [
          { kind: 'gainMoney', amount: 2 },
          { kind: 'gainPoints', amount: 1 },
        ],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'boxcars',
    name: 'Boxcars',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 3 },
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'grave-engine',
    name: 'Grave Engine',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 3 }, then: [{ kind: 'gainPoints', amount: 1 }] },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'double-down',
    name: 'Double Down',
    color: 'black',
    rarity: 'rare',
    cost: 7,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'midnight-jackpot',
    name: 'Midnight Jackpot',
    color: 'black',
    rarity: 'rare',
    cost: 9,
    legalSlots: [2, 12],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false }, // only the true doubles sums pay out
        then: [{ kind: 'gainPoints', amount: 5 }],
      },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'crypt-hoard',
    name: 'Crypt Hoard',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'legion-of-echoes',
    name: 'Legion of Echoes',
    color: 'black',
    rarity: 'rare',
    cost: 9,
    legalSlots: [6, 12],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
];

// GREEN "Wildgrove": odd slots {1,3,5} + odd sums {3,5,9}. Odd-dice parity
// payoffs and shop economy (discounts, refreshes). Echo flavor: money trickle.
export const GREEN_CARDS: CardDef[] = [
  {
    id: 'clover',
    name: 'Clover',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'odd-jobs',
    name: 'Odd Jobs',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'thrift-sprout',
    name: 'Thrift Sprout',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'market-vine',
    name: 'Market Vine',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 5],
    active: [{ kind: 'refreshShop' }, { kind: 'discount', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'crooked-scales',
    name: 'Crooked Scales',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [3, 5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'seedling-swap',
    name: 'Seedling Swap',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 3, 5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'ninth-harvest',
    name: 'Ninth Harvest',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'bargain-bloom',
    name: 'Bargain Bloom',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [{ kind: 'discount', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'wild-growth',
    name: 'Wild Growth',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'odd-omen',
    name: 'Odd Omen',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [5],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'verdant-engine',
    name: 'Verdant Engine',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 3, 5],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'harvest-moon',
    name: 'Harvest Moon',
    color: 'green',
    rarity: 'rare',
    cost: 9,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-trellis',
    name: 'Golden Trellis',
    color: 'green',
    rarity: 'rare',
    cost: 7,
    legalSlots: [3, 5],
    active: [
      { kind: 'refreshShop' },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'thicket-of-threes',
    name: 'Thicket of Threes',
    color: 'green',
    rarity: 'rare',
    cost: 7,
    legalSlots: [3],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'everbloom',
    name: 'Everbloom',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [5, 9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
];

// YELLOW "Gildmint": slots {2,4} + the unclaimed middle sums {6,8}. Raw coin
// generation plus trades that flip coins into points or HP. Echo: money.
export const YELLOW_CARDS: CardDef[] = [
  {
    id: 'penny-mint',
    name: 'Penny Mint',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [2],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'coin-press',
    name: 'Coin Press',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 4],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'money-changer',
    name: 'Money Changer',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-goose',
    name: 'Golden Goose',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [6],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tollbooth',
    name: 'Tollbooth',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'exchange-window',
    name: 'Exchange Window',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [4, 6],
    active: [{ kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'piggy-bank',
    name: 'Piggy Bank',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 1, then: [{ kind: 'heal', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'gilded-scale',
    name: 'Gilded Scale',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mint-condition',
    name: 'Mint Condition',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [2, 4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'eight-ball',
    name: 'Eight Ball',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 4, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'midas-touch',
    name: 'Midas Touch',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [6, 8],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'royal-mint',
    name: 'Royal Mint',
    color: 'yellow',
    rarity: 'rare',
    cost: 9,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'alchemists-ledger',
    name: "Alchemist's Ledger",
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [2, 4],
    active: [{ kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 2 }] }],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'fort-knox',
    name: 'Fort Knox',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [4, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'trade', pay: 5, then: [{ kind: 'gainPoints', amount: 4 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'counting-house',
    name: 'Counting House',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 2, then: [{ kind: 'heal', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
];

export function pools() {
  return {
    red: RED_CARDS,
    blue: BLUE_CARDS,
    black: BLACK_CARDS,
    green: GREEN_CARDS,
    yellow: YELLOW_CARDS,
    colorless: COLORLESS_CARDS,
  };
}
