import type { CardDef } from '../engine/types';

// The PLAN.md section 4 exemplar cards, verbatim. Placeholders, NOT balanced;
// the pool grows to targets (~15/color + ~10 colorless) in Phase 5 and gets
// tuned by the sim harness, never by intuition.

const ALL_SLOTS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
// Premium artifacts install high only (2026-07-13: colorless was bought too
// often; the strongest pieces now live where fires are rare and echoes carry).
const HIGH_SLOTS = [7, 8, 9, 10, 11, 12];

export const RED_CARDS: CardDef[] = [
  {
    id: 'cinder-bolt',
    name: 'Cinder Bolt',
    icon: 'Ability_Mage_FireStarter.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 5],
    active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'stoke-the-forge',
    name: 'Stoke the Forge',
    icon: 'Achievement_Zone_Ironforge.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [4, 6],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'blood-for-power',
    name: 'Blood for Power',
    icon: 'ability_deathwing_bloodcorruption_earth.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 7,
    legalSlots: [5, 6],
    active: [
      { kind: 'damage', amount: 2, target: 'roller' }, // self-risk: your own turn, you are the roller
      { kind: 'gainPoints', amount: 3 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'meteor-call',
    name: 'Meteor Call',
    icon: 'Spell_Mage_Meteor.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [10, 11, 12],
    active: [
      { kind: 'damage', amount: 4, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  // --- P5 batch ---
  {
    id: 'ember-jab',
    name: 'Ember',
    icon: 'INV_Elemental_Mote_Fire01.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [4],
    active: [
      { kind: 'damage', amount: 1, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'kindling-rage',
    name: 'Kindling Rage',
    icon: 'Spell_Nature_ShamanRage.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [5, 6],
    active: [
      { kind: 'damage', amount: 1, target: 'chooseOpponent' },
      {
        kind: 'conditional',
        when: { sumAtLeast: 9 },
        then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }],
      },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'bellows',
    name: 'Bellows',
    icon: 'INV_Archaeology_Orcclans_Bellow.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 10 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'blood-tithe',
    name: 'Blood Tithe',
    icon: 'Ability_IronMaidens_CorruptedBlood.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [4, 5],
    active: [
      { kind: 'damage', amount: 1, target: 'roller' },
      { kind: 'gainMoney', amount: 3 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'cauterize',
    name: 'Cauterize',
    icon: 'Ability_DemonHunter_ChaoticImprint_Fire.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3, // tuning 2026-07-13: -18 delta; the clutch heal for the blood color
    legalSlots: [4, 6],
    active: [
      { kind: 'heal', amount: 2 },
      { kind: 'conditional', when: { hpAtOrBelow: 10 }, then: [{ kind: 'heal', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'powder-keg',
    name: 'Powder Keg',
    icon: 'INV_Engineering_Gunpack.PNG',
    color: 'red',
    rarity: 'common',
    cost: 5,
    legalSlots: [4, 5, 6],
    active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'wildfire',
    name: 'Wildfire',
    icon: 'Ability_Racial_FireResist.PNG',
    color: 'red',
    rarity: 'common',
    cost: 5,
    legalSlots: [9, 10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'flare-up',
    name: 'Flare-Up',
    icon: 'Spell_Fire_Flare.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'martyrs-flame',
    name: "Martyr's Flame",
    icon: 'Spell_Nature_UnleashedRage.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 7,
    legalSlots: [4, 5],
    active: [
      { kind: 'damage', amount: 2, target: 'roller' },
      { kind: 'damage', amount: 3, target: 'chooseOpponent' },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'inferno-engine',
    name: 'Inferno Engine',
    icon: 'ABILITY_WARLOCK_INFERNO.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [11, 12],
    active: [{ kind: 'damage', amount: 5, target: 'chooseOpponent' }],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }], // tuning 2026-07-13 round 2
  },
  {
    id: 'cinder-crown',
    name: 'Cinder Crown',
    icon: 'INV_Crown_13.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8, // tuning 2026-07-13: -13 delta at cost 9
    legalSlots: [10, 11],
    active: [
      { kind: 'damage', amount: 3, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 2 },
      // tuning 2026-07-13 round 2: was sumAtLeast 11, which can never pay in
      // slot 10 (a slot-10 hit means the sum was exactly 10) - a dead bonus.
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }],
  },
  // --- 2026-07-13 high-band batch (Jake: 5 new 7-12 cards per color) ---
  {
    id: 'ember-storm',
    name: 'Ember Storm',
    icon: 'ability_warlock_burningembers.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [9, 10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'conditional', when: { sumAtLeast: 10 }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'backdraft',
    name: 'Backdraft',
    icon: 'Ability_Warlock_Backdraft.PNG',
    color: 'red',
    rarity: 'common',
    cost: 4,
    legalSlots: [10],
    active: [
      { kind: 'damage', amount: 2, target: 'chooseOpponent' },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 1, target: 'roller' }],
  },
  {
    id: 'slow-burn',
    name: 'Slow Burn',
    icon: 'INV_Jewelcrafting_Pyrestone_01.PNG',
    color: 'red',
    rarity: 'common',
    cost: 3,
    legalSlots: [9],
    // Echo-centric: cover it and every heard 9 singes the roller.
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }],
  },
  {
    id: 'eruption',
    name: 'Eruption',
    icon: 'Ability_Rhyolith_Volcano.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 9,
    legalSlots: [11, 12],
    active: [
      { kind: 'damage', amount: 4, target: 'chooseOpponent' },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'damage', amount: 2, target: 'roller' }],
  },
  {
    id: 'pyre-of-glory',
    name: 'Pyre of Glory',
    icon: 'INV_Inscription_Tarot_VolcanoCard.PNG',
    color: 'red',
    rarity: 'rare',
    cost: 8,
    legalSlots: [10, 11],
    active: [
      { kind: 'damage', amount: 1, target: 'roller' },
      { kind: 'gainPoints', amount: 4 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  // --- 2026-07-14 full-coverage batch (Jake: every color on every slot).
  // Red spreads onto 1-3 and 7-8 with SMALL burns; the big damage stays high.
  { id: 'spark', name: 'Spark', icon: 'Ability_Mage_Flamecannon.PNG', color: 'red', rarity: 'common', cost: 3, legalSlots: [1], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { sumAtLeast: 9 }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'cinder-snap', name: 'Cinder Snap', icon: 'Ability_Essence_ReapingFlames.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [1, 2], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'stoke-the-coals', name: 'Stoke the Coals', icon: 'INV_Pet_ScorchedStone.PNG', color: 'red', rarity: 'common', cost: 3, legalSlots: [2], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'first-flame', name: 'First Flame', icon: 'Ability_Racial_ForegedinFlames.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [1, 3], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'tinderbox', name: 'Tinderbox', icon: 'Ability_Mage_WorldInFlames.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [3], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'burning-hands', name: 'Burning Hands', icon: 'ABILITY_MAGE_MOLTENARMOR.PNG', color: 'red', rarity: 'common', cost: 5, legalSlots: [2, 3], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'seven-alarm-fire', name: 'Seven Alarm Fire', icon: 'Spell_Mage_InfernoBlast.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [7], active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'damage', amount: 1, target: 'roller' }] },
  { id: 'lucky-match', name: 'Lucky Match', icon: 'Ability_Mage_GreaterPyroblast.PNG', color: 'red', rarity: 'common', cost: 5, legalSlots: [7], active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }, { kind: 'gainPoints', amount: 1 }], echo: [{ kind: 'damage', amount: 1, target: 'roller' }] },
  { id: 'slag-furnace', name: 'Slag Furnace', icon: 'Achievement_Boss_Forgemaster.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [8], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'damage', amount: 1, target: 'chooseOpponent' }], echo: [{ kind: 'damage', amount: 2, target: 'roller' }] },
  { id: 'blast-wave', name: 'Blast Wave', icon: 'Ability_Foundryraid_BlastWave.PNG', color: 'red', rarity: 'common', cost: 5, legalSlots: [8], active: [{ kind: 'damage', amount: 3, target: 'chooseOpponent' }, { kind: 'damage', amount: 1, target: 'roller' }], echo: [{ kind: 'damage', amount: 1, target: 'roller' }] },
  { id: 'wildfire-front', name: 'Wildfire Front', icon: 'Spell_Fire_Ragnaros_MoltenInferno.PNG', color: 'red', rarity: 'rare', cost: 8, legalSlots: [7, 8], active: [{ kind: 'damage', amount: 3, target: 'chooseOpponent' }, { kind: 'gainPoints', amount: 1 }], echo: [{ kind: 'damage', amount: 2, target: 'roller' }] },
  { id: 'molten-torrent', name: 'Molten Torrent', icon: 'Spell_BurningBladeShaman_Molten_Torrent.PNG', color: 'red', rarity: 'common', cost: 5, legalSlots: [9, 10], active: [{ kind: 'damage', amount: 3, target: 'chooseOpponent' }], echo: [{ kind: 'damage', amount: 1, target: 'roller' }] },
  { id: 'lava-pool', name: 'Lava Pool', icon: 'Ability_Rhyolith_LavaPool.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [4, 5], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'ember-tithe', name: 'Ember Tithe', icon: 'Ability_Warlock_MoltenCore.PNG', color: 'red', rarity: 'common', cost: 3, legalSlots: [5, 6], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'molten-corgi', name: 'Molten Corgi', icon: 'INV_moltenCorgi.PNG', color: 'red', rarity: 'common', cost: 3, legalSlots: [1], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'grapeshot', name: 'Grapeshot', icon: 'Ability_IronMaidens_GrapeshotBlast.PNG', color: 'red', rarity: 'common', cost: 4, legalSlots: [2, 4], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'conditional', when: { allocatedIndividually: true }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'focused-blast', name: 'Focused Blast', icon: 'Ability_FelArakkoa_FocusedBlast.PNG', color: 'red', rarity: 'common', cost: 5, legalSlots: [3, 6], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'massive-blast', name: 'Massive Blast', icon: 'Ability_BossMannoroth_MassiveBlast.PNG', color: 'red', rarity: 'rare', cost: 8, legalSlots: [11], active: [{ kind: 'damage', amount: 4, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'damage', amount: 2, target: 'roller' }] },
  { id: 'scorched-earth', name: 'Scorched Earth', icon: 'Ability_Mage_ScorchedEarth.PNG', color: 'red', rarity: 'rare', cost: 7, legalSlots: [7, 9], active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }, { kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'damage', amount: 2, target: 'roller' }] },
  { id: 'forge-of-souls', name: 'Forge of Souls', icon: 'Achievement_Dungeon_Icecrown_ForgeofSouls.PNG', color: 'red', rarity: 'rare', cost: 9, legalSlots: [8, 10], active: [{ kind: 'damage', amount: 3, target: 'chooseOpponent' }, { kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'world-in-flames', name: 'World in Flames', icon: 'ABILITY_WARLOCK_INFERNO.PNG', color: 'red', rarity: 'rare', cost: 8, legalSlots: [12], active: [{ kind: 'damage', amount: 5, target: 'chooseOpponent' }, { kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'damage', amount: 2, target: 'roller' }] },
  { id: 'pilot-light', name: 'Pilot Light', icon: 'INV_Enchanting_70_Pet_Torch.PNG', color: 'red', rarity: 'common', cost: 3, legalSlots: [1, 6], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  // --- 2026-07-14 mechanics batch: the long fuse charges up to a haymaker.
  { id: 'long-fuse', name: 'Long Fuse', icon: 'Ability_Blackhand_Slagbombs.PNG', color: 'red', rarity: 'rare', cost: 7, legalSlots: [4, 5], active: [{ kind: 'charge', need: 5, then: [{ kind: 'damage', amount: 6, target: 'chooseOpponent' }] }], echo: [{ kind: 'damage', amount: 1, target: 'roller' }] },
];

export const BLUE_CARDS: CardDef[] = [
  {
    id: 'ripple',
    name: 'Ripple',
    icon: 'Ability_Shaman_FortifyingWaters.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [2, 3],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'second-glance',
    name: 'Second Glance',
    icon: 'Sha_Ability_Rogue_BloodyEye.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainToken', token: 'reroll', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'chronoloop',
    name: 'Chronoloop',
    icon: 'Spell_Mage_AlterTime_Active.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 7,
    legalSlots: [1, 3],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { allocatedIndividually: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'tide-engine',
    name: 'Tidal Totem',
    icon: 'Ability_Shaman_HealingTide.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 2, 3],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- P5 batch ---
  {
    id: 'tide-pool',
    name: 'Tide Pool',
    icon: 'INV_Misc_Food_Legion_GooAmberPurple_pool.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [
      { kind: 'gainMoney', amount: 2 }, // tuning 2026-07-13: was 1 (-11 delta)
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'undertow',
    name: 'Undertow',
    icon: 'Ability_ShaWaterElemental_Swirl.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainMoney', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'driftwood',
    name: 'Driftwood',
    icon: 'INV_Archaeology_80_Witch_EtchedDrustBone.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3,
    legalSlots: [3],
    active: [{ kind: 'gainPoints', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'spyglass',
    name: 'Spyglass',
    icon: 'INV_Misc_Spyglass_02.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 3, // tuning 2026-07-13: -10 delta at both counts
    legalSlots: [1, 2],
    active: [{ kind: 'refreshShop' }, { kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'current-reader',
    name: 'Flowing Current',
    icon: 'Spell_Mage_IceFlows.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 2, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mooring-line',
    name: 'Icy Breeze',
    icon: 'Spell_Frost_ArcticWinds.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
    ],
    // tuning 2026-07-13: slot-7 echoes hear every sum now; a point echo is the payoff
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'seventh-wave',
    name: 'Seventh Wave',
    icon: 'Spell_AnimaArdenweald_Wave.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4, // tuning 2026-07-13: worst high card at 2p (40% buyer win)
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'ebb-gate',
    name: 'Ebb Gate',
    icon: 'Spell_Shaman_HighTide.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 7],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tempest-loom',
    name: 'Arcane Tempest',
    icon: 'spell_Mage_NetherTempest.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainToken', token: 'reroll', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tidal-crown',
    name: 'Tidal Crown',
    icon: 'Item_icecrownringD.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 9,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 3 },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'mirror-bay',
    name: 'Mirror Bay',
    icon: 'Trade_Archaeology_HighborneSoulMirror.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 7,
    legalSlots: [2, 3],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'refreshShop' },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: blue's sum territory is the 7 ---
  {
    id: 'lucky-seven',
    name: 'Lucky Seven',
    icon: 'INV_Misc_Dice_01.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainToken', token: 'reroll', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'riptide',
    name: 'Riptide',
    icon: 'Spell_Nature_Riptide.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 4,
    legalSlots: [7],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'seventh-sense',
    name: 'Seventh Sense',
    icon: 'INV_Inscription_TarotIllusion.PNG',
    color: 'blue',
    rarity: 'common',
    cost: 5,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainToken', token: 'nudge', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'crest-of-the-wave',
    name: 'Crest of the Wave',
    icon: 'Spell_Shaman_TidalWaves.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 8,
    legalSlots: [7],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'maelstrom',
    name: 'Maelstrom',
    icon: 'Spell_Shaman_MaelstromWeapon.PNG',
    color: 'blue',
    rarity: 'rare',
    cost: 9,
    legalSlots: [7],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  // --- 2026-07-14 full-coverage batch: blue flows onto 6 and 8-12 with
  // steady money/points and the occasional token; the tricks stay low.
  { id: 'cold-snap', name: 'Cold Snap', icon: 'ability_deathknight_pillaroffrost.PNG', color: 'blue', rarity: 'common', cost: 3, legalSlots: [6], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'frost-jaw', name: 'Frost Jaw', icon: 'Ability_Mage_FrostJaw.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [6], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'gainToken', token: 'reroll', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'ice-shard', name: 'Ice Shard', icon: 'Spell_Frost_IceShard.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [6, 8], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'gainPoints', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'water-jet', name: 'Water Jet', icon: 'Ability_Mage_WaterJet.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [8], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'gainToken', token: 'nudge', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'arcane-barrage', name: 'Arcane Barrage', icon: 'Ability_Mage_ArcaneBarrage.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [8, 9], active: [{ kind: 'gainPoints', amount: 1 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'healing-tide', name: 'Healing Tide', icon: 'Ability_Shaman_HealingTide.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [9], active: [{ kind: 'heal', amount: 2 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'heal', amount: 1 }] },
  { id: 'deep-current', name: 'Deep Current', icon: 'Ability_Shaman_FortifyingWaters.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [9], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'gainPoints', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'mana-storm', name: 'Mana Storm', icon: 'Achievement_Dungeon_TheOtherSide_TheManaStorms.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [10], active: [{ kind: 'gainMoney', amount: 3 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'frostfire', name: 'Frostfire', icon: 'Ability_Mage_FrostFireBolt.PNG', color: 'blue', rarity: 'rare', cost: 7, legalSlots: [10, 11], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 1 }, { kind: 'gainToken', token: 'reroll', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'ray-of-frost', name: 'Ray of Frost', icon: 'Ability_Mage_RayofFrost.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [11], active: [{ kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'throne-of-tides', name: 'Throne of the Tides', icon: 'Achievement_Dungeon_Throne of the Tides.PNG', color: 'blue', rarity: 'rare', cost: 8, legalSlots: [12], active: [{ kind: 'gainPoints', amount: 4 }], echo: [{ kind: 'gainPoints', amount: 2 }] },
  { id: 'ozumat', name: 'Ozumat', icon: 'Achievement_Dungeon_Throne of the Tides_Ozumat.PNG', color: 'blue', rarity: 'rare', cost: 9, legalSlots: [12], active: [{ kind: 'gainMoney', amount: 4 }, { kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'bubble', name: 'Bubble', icon: 'Creatureportrait_Bubble.PNG', color: 'blue', rarity: 'common', cost: 3, legalSlots: [1, 6], active: [{ kind: 'gainToken', token: 'nudge', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'water-shield', name: 'Water Shield', icon: 'Ability_Shaman_WaterShield.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [2, 6], active: [{ kind: 'heal', amount: 1 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'heal', amount: 1 }] },
  { id: 'mana-tree', name: 'Mana Tree', icon: 'Ability_Druid_ManaTree.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [3, 9], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'gainToken', token: 'reroll', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'chaotic-imprint', name: 'Chaotic Imprint', icon: 'Ability_DemonHunter_ChaoticImprint_Frost.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [4, 8], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'arcane-affinity', name: 'Arcane Affinity', icon: 'Ability_Racial_ArcaneAffinity.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [5, 7], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'gainToken', token: 'nudge', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'tidesage', name: 'Tidesage Council', icon: 'Achievement_Dungeon_TidesageCouncil.PNG', color: 'blue', rarity: 'rare', cost: 8, legalSlots: [7, 9], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 1 }, { kind: 'gainToken', token: 'reroll', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'force-sphere', name: 'Force Sphere', icon: 'Ability_Monk_ForceSphere_arcane.PNG', color: 'blue', rarity: 'rare', cost: 8, legalSlots: [10, 12], active: [{ kind: 'gainPoints', amount: 3 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'water-strider', name: 'Water Strider', icon: 'Ability_Mount_WaterStriderMount.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [2, 8], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'gainToken', token: 'reroll', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'conjure-eleven', name: 'Conjure Eleven', icon: 'Ability_Mage_ConjureWater11.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [1, 11], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'mana-break', name: 'Mana Break', icon: 'Ability_DemonHunter_ManaBreak.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [6, 10], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  // --- 2026-07-14 mechanics batch: blue gets precise chill damage + the
  // signature board swap (your 2 and your 12 trade places... until it fires
  // again and the tides turn back).
  { id: 'ice-lance', name: 'Ice Lance', icon: 'Spell_Frost_Frostbolt.PNG', color: 'blue', rarity: 'common', cost: 4, legalSlots: [2, 3], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'gainToken', token: 'reroll', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'deep-freeze', name: 'Deep Freeze', icon: 'Spell_Frost_FrostBolt02.PNG', color: 'blue', rarity: 'common', cost: 5, legalSlots: [7], active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'mirror-current', name: 'Mirror Current', icon: 'Spell_Nature_MirrorImage.PNG', color: 'blue', rarity: 'rare', cost: 8, legalSlots: [4], active: [{ kind: 'swapBoard', a: 2, b: 12 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
];

// Colorless = MARKET ARTIFACTS (2026-07-13): a shared static shop all players
// compete over. Stronger than color cards, priced 8-14, any slot at purchase.
export const COLORLESS_CARDS: CardDef[] = [
  {
    id: 'coin-sprite',
    name: 'Coin Sprite',
    icon: 'INV_Misc_AzsharaCoin2.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13: -9 delta at 4p
  },
  {
    id: 'lucky-charm',
    name: 'Lucky Charm',
    icon: 'INV_Jewelry_Necklace_03.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 10, // tuning 2026-07-13: +6 delta at both counts
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'prism-core',
    name: 'Prism Core',
    icon: 'INV_Enchant_ShardPrismaticLarge.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 12, // tuning 2026-07-13: +16 delta at 4p, the strongest card in the pool
    legalSlots: HIGH_SLOTS,
    active: [{ kind: 'gainPoints', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tin-totem',
    name: 'Steel Totem',
    icon: 'Spell_Nature_WrathofAir_Totem.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      // tuning 2026-07-13: threshold 12 -> 15 (HP pools are 22/18/16 by player count)
      { kind: 'conditional', when: { hpAtOrBelow: 15 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'barter-stone',
    name: 'Barter Stone',
    icon: 'INV_Misc_Archstone_01.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7, // tuning 2026-07-13
    legalSlots: ALL_SLOTS,
    active: [{ kind: 'gainMoney', amount: 4 }, { kind: 'refreshShop' }], // tuning round 2
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'keepsake',
    name: 'Keepsake',
    icon: 'INV_Ring_Bastion_01_Silver.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'gainPoints', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: true },
        then: [{ kind: 'gainPoints', amount: 1 }],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'medic-kit',
    name: 'Medic Kit',
    icon: 'INV_FIRST_AID_70_MedicalKit.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 7,
    legalSlots: ALL_SLOTS,
    active: [
      { kind: 'heal', amount: 3 }, // tuning 2026-07-13
      { kind: 'gainMoney', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'hoard-charm',
    name: 'Hoard Charm',
    icon: 'INV_Archaeology_70_Highborne_InertLeystoneCharm.PNG',
    color: 'colorless',
    rarity: 'common',
    cost: 8, // tuning 2026-07-13
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'gainMoney', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-idol',
    name: 'Golden Idol',
    icon: 'INV_QirajIdol_Sun.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 11,
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'phoenix-plate',
    name: 'Phoenix Plate',
    icon: 'INV_CHEST_CLOTH_68.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 12,
    legalSlots: HIGH_SLOTS,
    active: [
      { kind: 'heal', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { hpAtOrBelow: 10 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    // The Space Base homage: fire this slot seven times and just... win.
    id: 'doomsday-device',
    name: 'Doomsday Device',
    icon: 'Ability_IronMaidens_DetonationSequence.PNG',
    color: 'colorless',
    rarity: 'rare',
    cost: 14,
    legalSlots: HIGH_SLOTS,
    active: [{ kind: 'charge', need: 7, then: [{ kind: 'winGame' }] }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
];

// BLACK "Gravebound": slots {1,6} + doubles-only sums {2,12}. Doubles payoffs
// and echo-stack (graveyard) synergy. Echo flavor: points from the grave.
export const BLACK_CARDS: CardDef[] = [
  {
    id: 'grave-tithe',
    name: 'Grave Tithe',
    icon: 'Ability_Argus_DeathFog.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'bone-dice',
    name: 'Bone Dice',
    icon: 'Ability_Rogue_RolltheBones.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'shallow-grave',
    name: 'Shallow Grave',
    icon: 'Achievement_BG_Xkills_AVgraveyard.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mourners-coin',
    name: "Mourner's Coin",
    icon: 'INV_Misc_AzsharaCoin.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      // tuning 2026-07-13: doubles bonus 2 -> 3
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainMoney', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'six-feet-under',
    name: 'Six Feet Under',
    icon: 'Ability_FiegnDead.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      // tuning 2026-07-13: threshold 5 -> 4
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'snake-eyes',
    name: 'Snake Eyes',
    icon: 'INV_GiantSnake_Black.PNG',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false }, // the true snake eyes: sum 2 = double 1s
        then: [
          { kind: 'gainPoints', amount: 4 },
          { kind: 'gainMoney', amount: 1 },
        ],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'pallbearer',
    name: 'Pallbearer',
    icon: 'INV_Axe_2H_UndeadGuitar_C_01.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [6],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'echo-chamber',
    name: 'Echo Chamber',
    icon: 'Achievement_Scenario_TombofForgottenKings.PNG',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 8 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'death-rattle',
    name: 'Death Rattle',
    icon: 'Spell_Shadow_RaiseDead.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [2],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false },
        then: [
          { kind: 'gainMoney', amount: 2 },
          { kind: 'gainPoints', amount: 1 },
        ],
      },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'boxcars',
    name: "Death's Advance",
    icon: 'INV_SkeletalWarhorse_01_Brown.PNG',
    color: 'black',
    rarity: 'common',
    cost: 5,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 4 }, // tuning 2026-07-13: sum 12 is 1/36; jackpot or nothing
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'grave-engine',
    name: 'Grave Engine',
    icon: 'INV_Engineering_90_GhostTrap.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainPoints', amount: 1 }] },
      { kind: 'conditional', when: { echoStackAtLeast: 8 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'double-down',
    name: 'Double Down',
    icon: 'Ability_DemonHunter_DoubleJump.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 7,
    legalSlots: [1, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      // tuning 2026-07-13: doubles jackpot 3 -> 4
      { kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainPoints', amount: 4 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'midnight-jackpot',
    name: 'Midnight Jackpot',
    icon: 'ability_rogue_dirtydeeds.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 9,
    legalSlots: [2, 12],
    active: [
      { kind: 'gainMoney', amount: 1 },
      {
        kind: 'conditional',
        when: { allocatedIndividually: false }, // only the true doubles sums pay out
        then: [{ kind: 'gainPoints', amount: 5 }],
      },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'crypt-hoard',
    name: 'Crypt Hoard',
    icon: 'Battleground_Strongbox_Gold_Horde.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'legion-of-echoes',
    name: 'Legion of Echoes',
    icon: 'Ability_Shaman_EchooftheElements.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 9,
    legalSlots: [6, 12],
    // Nerfed 2026-07-14: the flat point-per-fire on slot 6 ran away in the
    // full-coverage meta (67% buyer win rate). The legion must assemble first.
    active: [
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainPoints', amount: 1 }] },
      { kind: 'conditional', when: { echoStackAtLeast: 8 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: black's sum territory is the 12 ---
  {
    id: 'graveyard-shift',
    name: 'Graveyard Shift',
    icon: 'INV_GraveGolemPet.PNG',
    color: 'black',
    rarity: 'common',
    cost: 3,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'last-rites',
    name: 'Last Rites',
    icon: 'Spell_Shadow_DarkRitual.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { echoStackAtLeast: 4 }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'tombstone',
    name: 'Tombstone',
    icon: '70_inscription_vantus_rune_tomb.PNG',
    color: 'black',
    rarity: 'common',
    cost: 4,
    legalSlots: [12],
    active: [{ kind: 'gainMoney', amount: 4 }],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'dead-mans-hand',
    name: "Dead Man's Hand",
    icon: 'INV_Inscription_TarotDeath.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 8,
    legalSlots: [12],
    active: [
      { kind: 'gainPoints', amount: 4 },
      { kind: 'conditional', when: { echoStackAtLeast: 7 }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'ossuary',
    name: 'Ossuary',
    icon: 'Achievement_Dungeon_TombOfSargeras.PNG',
    color: 'black',
    rarity: 'rare',
    cost: 7,
    legalSlots: [12],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  // --- 2026-07-14 full-coverage batch: black seeps into the mid-board with
  // graveyard-counting payoffs; doubles tricks only where doubles can land.
  { id: 'brittle-bones', name: 'Brittle Bones', icon: 'ability_deathknight_brittlebones.PNG', color: 'black', rarity: 'common', cost: 3, legalSlots: [3], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'bone-shield', name: 'Bone Shield', icon: 'ability_deathknight_boneshield.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [3, 4], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'cursed-idol', name: 'Cursed Idol', icon: 'Ability_Creature_Cursed_02.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [4], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'witchs-skull', name: "Witch's Skull", icon: 'INV_Archaeology_80_Witch_Skull.PNG', color: 'black', rarity: 'common', cost: 3, legalSlots: [5], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'laughing-skull', name: 'Laughing Skull', icon: 'INV_Helm_LaughingSkull_01.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [5, 6], active: [{ kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainMoney', amount: 3 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'shadow-bolt', name: 'Shadow Bolt', icon: 'Spell_Shadow_ShadowBolt.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [7], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'seventh-seal', name: 'Seventh Seal', icon: 'INV_Encrypted06.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [7], active: [{ kind: 'gainPoints', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'plague-barrel', name: 'Plague Barrel', icon: 'Ability_Vehicle_PlagueBarrel.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [8], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'wasting-plague', name: 'Wasting Plague', icon: 'Ability_Argus_WastingPlague.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [8, 9], active: [{ kind: 'gainPoints', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 2 }] }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'raven-omen', name: 'Raven Omen', icon: 'INV-Mount_Raven_54.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [9], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'ravencrest', name: 'Ravencrest', icon: 'INV_Belt_Plate_LordRavencrest_B_01.PNG', color: 'black', rarity: 'rare', cost: 7, legalSlots: [10], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'plaguefall', name: 'Plaguefall', icon: 'Achievement_Dungeon_PlagueFall.PNG', color: 'black', rarity: 'rare', cost: 8, legalSlots: [10, 11], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'curse-of-eleven', name: 'Curse of Eleven', icon: 'Ability_Creature_Cursed_05.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [11], active: [{ kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'skull-dagger', name: 'Skull Dagger', icon: 'INV_Knife_1H_ArtifactSkullofEredar_D_01.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [3, 7], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'chilled-to-the-bone', name: 'Chilled to the Bone', icon: 'Ability_Mage_ChilledToTheBone.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [4, 8], active: [{ kind: 'conditional', when: { rolledDoubles: true }, then: [{ kind: 'gainMoney', amount: 3 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'cursed-hoard', name: 'Cursed Hoard', icon: 'Ability_Creature_Cursed_03.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [5, 9], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'plague-doctor', name: 'Plague Doctor', icon: 'Achievement_Dungeon_PlagueFall_DoctorIckus.PNG', color: 'black', rarity: 'rare', cost: 7, legalSlots: [9, 10], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 2 }] }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'venom-blade', name: 'Venom Blade', icon: 'Achievement_Dungeon_PlagueFall_DominaVenomBlade.PNG', color: 'black', rarity: 'rare', cost: 8, legalSlots: [7, 11], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'conditional', when: { echoStackAtLeast: 7 }, then: [{ kind: 'gainPoints', amount: 2 }] }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'eredar-relic', name: 'Eredar Relic', icon: 'INV_Knife_1H_ArtifactSkullofEredar_D_02.PNG', color: 'black', rarity: 'common', cost: 4, legalSlots: [3, 12], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'cursed-scroll', name: 'Cursed Scroll', icon: 'Ability_Creature_Cursed_01.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [4, 10], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'bone-pile', name: 'Bone Pile', icon: 'INV_Bone_Skull_04.PNG', color: 'black', rarity: 'common', cost: 3, legalSlots: [5, 8], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'fire-raven', name: 'Fire Raven', icon: 'Ability_Mount_FireRavenGodMount.PNG', color: 'black', rarity: 'rare', cost: 9, legalSlots: [11, 12], active: [{ kind: 'gainPoints', amount: 3 }, { kind: 'conditional', when: { echoStackAtLeast: 6 }, then: [{ kind: 'gainPoints', amount: 2 }] }], echo: [{ kind: 'gainPoints', amount: 2 }] },
  // --- 2026-07-14 mechanics batch: black robs graves and swings scythes.
  { id: 'grave-robbery', name: 'Grave Robbery', icon: 'INV_Misc_Shovel_01.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [6], active: [{ kind: 'steal', amount: 1, target: 'chooseOpponent' }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'steal', amount: 1, target: 'roller' }] },
  { id: 'bone-scythe', name: 'Bone Scythe', icon: 'INV_Archaeology_80_Witch_BoneScythe.PNG', color: 'black', rarity: 'rare', cost: 8, legalSlots: [10, 12], active: [{ kind: 'damage', amount: 3, target: 'chooseOpponent' }, { kind: 'gainPoints', amount: 1 }], echo: [{ kind: 'damage', amount: 1, target: 'roller' }] },
  { id: 'hexblade', name: 'Hexblade', icon: 'INV_Archaeology_80_Witch_Dagger.PNG', color: 'black', rarity: 'common', cost: 5, legalSlots: [3, 5], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'conditional', when: { echoStackAtLeast: 5 }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
];

// GREEN "Wildgrove": odd slots {1,3,5} + odd sums {3,5,9}. Odd-dice parity
// payoffs and shop economy (discounts, refreshes). Echo flavor: money trickle.
export const GREEN_CARDS: CardDef[] = [
  {
    id: 'clover',
    name: 'Seedling',
    icon: 'Inv_Farm_PumpkinSeed_Green.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      // tuning 2026-07-13: odd-parity bonus 1 -> 2 (-8 delta)
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'odd-jobs',
    name: 'Odd Jobs',
    icon: 'INV_Engineering_90_WormholeGenerator.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 3],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'thrift-sprout',
    name: 'Thrift Sprout',
    icon: 'ABILITY_DRUID_NOURISH.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'market-vine',
    name: 'Market Vine',
    icon: 'INV_Misc_Herb_NightmareVine_Stem.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [1, 5],
    // tuning 2026-07-13: had no direct gain at all
    active: [{ kind: 'refreshShop' }, { kind: 'discount', amount: 1 }, { kind: 'gainMoney', amount: 1 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'crooked-scales',
    name: 'Crooked Scales',
    icon: 'INV_Misc_ElvenCoins.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [3, 5],
    active: [
      { kind: 'gainMoney', amount: 2 }, // tuning 2026-07-13: base 1 -> 2 (-8.5 delta)
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'seedling-swap',
    name: 'Sapling Swap',
    icon: 'SPELL_NATURE_HEALINGTOUCH.PNG',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [1, 3, 5],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'ninth-harvest',
    name: 'Ninth Harvest',
    icon: 'Spell_Warlock_HarvestofLife.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13: slot-9 echoes hear every sum now
  },
  {
    id: 'bargain-bloom',
    name: 'Bargain Bloom',
    icon: 'Achievement_Dungeon_Everbloom.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [1],
    active: [{ kind: 'discount', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'wild-growth',
    name: 'Wild Mushroom',
    icon: 'Druid_Ability_Wildmushroom_b.PNG',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13
  },
  {
    id: 'odd-omen',
    name: 'Odds and Ends',
    icon: 'Ability_Druid_Replenish.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [5],
    active: [
      { kind: 'gainPoints', amount: 1 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'verdant-engine',
    name: 'Verdant Engine',
    icon: 'INV_Inscription_Pigment_Verdant.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [1, 3, 5],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'harvest-moon',
    name: 'Harvest Moon',
    icon: 'artifactability_BalanceDruid_Fullmoon.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8, // tuning 2026-07-13
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-trellis',
    name: 'Golden Trellis',
    icon: 'INV_Misc_Herb_Nightmarevine.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 7,
    legalSlots: [3, 5],
    active: [
      { kind: 'refreshShop' },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'thicket-of-threes',
    name: 'Thicket of Threes',
    icon: 'Ability_Druid_ManaTree.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 7,
    legalSlots: [3],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'everbloom',
    name: 'Everbloom',
    icon: 'INV_Misc_Herb_Arrowbloom.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [5, 9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: green's sum territory is the 9. NOTE:
  // bothDiceOdd can never be true on a summed 9 (odd sums split odd+even),
  // so these stay parity-free on purpose - the cinder-crown lesson.
  {
    id: 'ninth-life',
    name: 'Ninth Life',
    icon: 'Ability_Druid_TreeofLife.PNG',
    color: 'green',
    rarity: 'common',
    cost: 3,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'moonlit-market',
    name: 'Moonlit Market',
    icon: 'Ability_Druid_ImprovedMoonkinForm.PNG',
    color: 'green',
    rarity: 'common',
    cost: 4,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'refreshShop' },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'autumn-tithe',
    name: 'Autumn Tithe',
    icon: 'Ability_Ardenweald_Paladin_Autumn.PNG',
    color: 'green',
    rarity: 'common',
    cost: 5,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'elder-grove',
    name: 'Elder Grove',
    icon: 'Ability_Druid_ProtectionOfTheGrove.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 8,
    legalSlots: [9],
    active: [
      { kind: 'gainPoints', amount: 2 },
      { kind: 'gainMoney', amount: 2 },
      { kind: 'discount', amount: 1 },
    ],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'season-of-plenty',
    name: 'Season of Plenty',
    icon: 'INV_Holiday_Thanksgiving_Cornucopia.PNG',
    color: 'green',
    rarity: 'rare',
    cost: 9,
    legalSlots: [9],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'gainPoints', amount: 2 },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  // --- 2026-07-14 full-coverage batch: green grows everywhere. Parity
  // bonuses only sit where the dice can satisfy them: both-odd works on even
  // sums (2 = 1+1, 8 = 3+5) and split odd faces, but NEVER on odd sums
  // (7/9/11 always split odd+even) or 12 (only 6+6) - the cinder-crown lesson.
  { id: 'herb-seed', name: 'Herb Seed', icon: 'Inv_Farm_HerbSeed.PNG', color: 'green', rarity: 'common', cost: 3, legalSlots: [2], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 2 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'golden-seed', name: 'Golden Seed', icon: 'Inv_Farm_GoldenSeed.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [2, 4], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'enchanted-seed', name: 'Enchanted Seed', icon: 'Inv_Farm_EnchantedSeed.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [4], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'stormvine', name: 'Stormvine', icon: 'INV_Misc_Herb_Stormvine.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [4, 6], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'conditional', when: { bothDiceEven: true }, then: [{ kind: 'gainMoney', amount: 2 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'nightmare-vine', name: 'Nightmare Vine', icon: 'INV_Misc_Herb_Nightmarevine.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [6], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'refreshShop' }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'goldthorn', name: 'Goldthorn', icon: 'INV_Misc_Herb_Goldthorn_Bramble.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [6, 8], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'lucky-bloom', name: 'Lucky Bloom', icon: 'INV_ Misc_Herb_Ardenweald.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [7], active: [{ kind: 'gainMoney', amount: 3 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'wild-mushroom', name: 'Wild Mushroom', icon: 'Druid_Ability_Wildmushroom_a.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [7], active: [{ kind: 'gainPoints', amount: 1 }, { kind: 'gainMoney', amount: 1 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'spore-cloud', name: 'Spore Cloud', icon: 'Creature_SporeMushroom.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [8], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'needle-mushroom', name: 'Needle Mushroom', icon: 'Inv_Misc_DriedNeedleMushrooms.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [8, 10], active: [{ kind: 'gainPoints', amount: 1 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'icethorn', name: 'Icethorn', icon: 'INV_Misc_Herb_IceThorn.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [10], active: [{ kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'everbloom-gold', name: 'Everbloom Gold', icon: 'Achievement_ChallengeMode_Everbloom_Gold.PNG', color: 'green', rarity: 'rare', cost: 8, legalSlots: [10, 11], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 2 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'thorn-necklace', name: 'Thorn Necklace', icon: 'inv_misc_thornnecklace.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [11], active: [{ kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'death-blossom', name: 'Death Blossom', icon: 'INV_ Misc_Herb_DeathBlossom.PNG', color: 'green', rarity: 'rare', cost: 7, legalSlots: [12], active: [{ kind: 'gainPoints', amount: 3 }, { kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'divine-harvest', name: 'Divine Harvest', icon: 'ABILITY_PALADIN_DIVINESTORM.PNG', color: 'green', rarity: 'rare', cost: 9, legalSlots: [12], active: [{ kind: 'gainPoints', amount: 4 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 2 }] },
  { id: 'bramble-wall', name: 'Bramble Wall', icon: 'INV_Misc_Herb_Icethorn_Bramble.PNG', color: 'green', rarity: 'common', cost: 3, legalSlots: [2, 6], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'kyparite-seed', name: 'Kyparite Seed', icon: 'Inv_Farm_KypariteSeed.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [4, 8], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'tough-seed', name: 'Tough Seed', icon: 'Inv_Farm_LeatherSeed.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [2, 10], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'stranglethorn', name: 'Stranglethorn', icon: 'Achievement_Zone_Stranglethorn_01.PNG', color: 'green', rarity: 'rare', cost: 7, legalSlots: [7, 11], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'nightmare-stem', name: 'Nightmare Stem', icon: 'INV_Misc_Herb_NightmareVine_Stem.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [3, 7], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'discount', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'seasons-turn', name: "Season's Turn", icon: 'Achievement_ChallengeMode_Everbloom_Hourglass.PNG', color: 'green', rarity: 'rare', cost: 8, legalSlots: [6, 12], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'petal-fall', name: 'Petal Fall', icon: 'INV_ Misc_Herb_DeathBlossom_Leaf.PNG', color: 'green', rarity: 'common', cost: 3, legalSlots: [1, 8], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'gainMoney', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  // --- 2026-07-14 mechanics batch: nature bites back, and rotates its crops.
  { id: 'thorn-lash', name: 'Thorn Lash', icon: 'INV_Misc_1h_FarmSickle_A_01.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [3, 5], active: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }, { kind: 'conditional', when: { bothDiceOdd: true }, then: [{ kind: 'damage', amount: 1, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'the-reaping', name: 'The Reaping', icon: 'INV_Misc_2h_FarmScythe_A_01.PNG', color: 'green', rarity: 'common', cost: 5, legalSlots: [9], active: [{ kind: 'damage', amount: 2, target: 'chooseOpponent' }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'crop-rotation', name: 'Crop Rotation', icon: 'INV_Misc_2h_FarmShovel_A_01.PNG', color: 'green', rarity: 'common', cost: 4, legalSlots: [1, 3], active: [{ kind: 'swapBoard', a: 4, b: 9 }, { kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
];

// YELLOW "Gildmint": slots {2,4} + the unclaimed middle sums {6,8}. Raw coin
// generation plus trades that flip coins into points or HP. Echo: money.
export const YELLOW_CARDS: CardDef[] = [
  {
    id: 'penny-mint',
    name: 'Penny Mint',
    icon: 'INV_Misc_Coin_05.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [2],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'coin-press',
    name: 'Coin Press',
    icon: 'Achievement_Dungeon_CoinOperatedCrowdPummeler.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 4],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'money-changer',
    name: 'Money Changer',
    icon: 'Ability_Racial_TimeIsMoney.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3, // tuning 2026-07-13: -10 delta at cost 4
    legalSlots: [4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'golden-goose',
    name: 'Rocket Chicken',
    icon: 'INV_Misc_EngGizmos_RocketChicken.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [6],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'tollbooth',
    name: 'Tollbooth',
    icon: 'INV_Misc_LuckyMoneyEnvelope.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 3 }],
    echo: [{ kind: 'gainMoney', amount: 2 }], // tuning 2026-07-13: the toll pays on others' turns
  },
  {
    id: 'exchange-window',
    name: 'Golden Salve',
    icon: 'Trade_Alchemy_PotionA4.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [4, 6],
    // tuning 2026-07-13: pure trade with no base gain ran -12
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'piggy-bank',
    name: 'Piggy Bank',
    icon: 'INV_BabyPig.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 1, then: [{ kind: 'heal', amount: 2 }] }, // tuning 2026-07-13
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'gilded-scale',
    name: 'Gilded Harp',
    icon: 'Inv_Misc_Trinket_GoldenHarp.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [2, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'conditional', when: { sumAtLeast: 8 }, then: [{ kind: 'gainMoney', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'mint-condition',
    name: 'Mint Condition',
    icon: 'INV_Misc_Coin_01.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [2, 4],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'eight-ball',
    name: 'Golden Nugget',
    icon: 'INV_Misc_Gem_GoldenDraenite_01.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 1 },
      { kind: 'trade', pay: 4, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'midas-touch',
    name: 'Midas Touch',
    icon: 'INV_MawGuardHandMountGold.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [6, 8],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'royal-mint',
    name: 'Royal Mint',
    icon: 'Achievement_ChallengeMode_Auchindoun_Gold.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 9,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'alchemists-ledger',
    name: "Alchemist's Ledger",
    icon: 'INV_Misc_Profession_Book_Alchemy.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [2, 4],
    active: [{ kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 2 }] }],
    echo: [{ kind: 'gainPoints', amount: 1 }],
  },
  {
    id: 'fort-knox',
    name: 'Fort Knox',
    icon: 'ACHIEVEMENT_GUILDPERK_MOBILEBANKING.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [4, 6],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'trade', pay: 5, then: [{ kind: 'gainPoints', amount: 4 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'counting-house',
    name: 'Counting House',
    icon: 'Ability_Racial_PackHobgoblin.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [6],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 2, then: [{ kind: 'heal', amount: 2 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  // --- 2026-07-13 high-band batch: yellow's sum territory is the 8 ---
  {
    id: 'loose-change',
    name: 'Loose Change',
    icon: 'Archaeology_5_0_MoguCoin.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 3,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 2 }],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'bullion',
    name: 'Bullion',
    icon: 'INV_Ingot_03.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 4,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 3 },
      { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'treasure-map',
    name: 'Treasure Map',
    icon: 'Icon_TreasureMap.PNG',
    color: 'yellow',
    rarity: 'common',
    cost: 5,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 2 },
      { kind: 'gainPoints', amount: 1 },
    ],
    echo: [{ kind: 'gainMoney', amount: 1 }],
  },
  {
    id: 'the-vault',
    name: 'The Vault',
    icon: 'achievement_dungeon_VaultoftheWardens.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 8,
    legalSlots: [8],
    active: [
      { kind: 'gainMoney', amount: 4 },
      { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 3 }] },
    ],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  {
    id: 'dragons-hoard',
    name: "Dragon's Hoard",
    icon: 'inv_misc_treasurechest01b.PNG',
    color: 'yellow',
    rarity: 'rare',
    cost: 7,
    legalSlots: [8],
    active: [{ kind: 'gainMoney', amount: 5 }],
    echo: [{ kind: 'gainMoney', amount: 2 }],
  },
  // --- 2026-07-14 full-coverage batch: yellow's coin engine reaches every
  // slot; trades stay its signature and scale up with the slot's rarity.
  { id: 'copper-penny', name: 'Copper Penny', icon: 'INV_Ring_Bastion_01_Gold.PNG', color: 'yellow', rarity: 'common', cost: 3, legalSlots: [1], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'pocket-lantern', name: 'Pocket Lantern', icon: 'INV_Misc_Lantern_01.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [1, 3], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'amulet-of-thrift', name: 'Amulet of Thrift', icon: 'INV_Jewelry_Amulet_01.PNG', color: 'yellow', rarity: 'common', cost: 3, legalSlots: [3], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'merchants-scales', name: "Merchant's Scales", icon: 'INV_MISC_DEEPSEASCALES.PNG', color: 'yellow', rarity: 'common', cost: 5, legalSlots: [3, 5], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 2 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'silver-amulet', name: 'Silver Amulet', icon: 'INV_Jewelry_Amulet_02.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [5], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'trade', pay: 2, then: [{ kind: 'heal', amount: 2 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'lucky-lantern', name: 'Lucky Lantern', icon: 'Inv_misc_trinket6oIH_lanternA1.PNG', color: 'yellow', rarity: 'common', cost: 5, legalSlots: [5, 7], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'seven-lanterns', name: 'Seven Lanterns', icon: 'Inv_misc_trinket6oIH_lanternB1.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [7], active: [{ kind: 'gainMoney', amount: 3 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'tricks-of-the-trade', name: 'Tricks of the Trade', icon: 'Ability_Rogue_TricksOftheTrade.PNG', color: 'yellow', rarity: 'rare', cost: 7, legalSlots: [7, 9], active: [{ kind: 'gainMoney', amount: 3 }, { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 2 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'gilded-ring', name: 'Gilded Ring', icon: 'INV_Ring_Bastion_02_Gold.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [9], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'dragon-scales', name: 'Dragon Scales', icon: 'INV_Artifact_DragonScales.PNG', color: 'yellow', rarity: 'common', cost: 5, legalSlots: [9, 10], active: [{ kind: 'gainMoney', amount: 3 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'jack-of-all-trades', name: 'Jack of All Trades', icon: 'Ability_Racial_JackofAllTrades.PNG', color: 'yellow', rarity: 'rare', cost: 7, legalSlots: [10], active: [{ kind: 'gainMoney', amount: 3 }, { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 3 }] }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'wise-judgement', name: 'Wise Judgement', icon: 'Ability_Paladin_JudgementoftheWise.PNG', color: 'yellow', rarity: 'rare', cost: 8, legalSlots: [10, 11], active: [{ kind: 'gainPoints', amount: 2 }, { kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'crown-of-heavens', name: 'Crown of Heavens', icon: 'Ability_Crown_of_the_Heavens_Icon.PNG', color: 'yellow', rarity: 'common', cost: 5, legalSlots: [11], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'gainPoints', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'signet-of-midnight', name: 'Signet of Midnight', icon: 'INV_Ring_Maldraxxus_01_Gold.PNG', color: 'yellow', rarity: 'rare', cost: 8, legalSlots: [11, 12], active: [{ kind: 'gainMoney', amount: 4 }, { kind: 'trade', pay: 3, then: [{ kind: 'gainPoints', amount: 3 }] }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'enlightened-vault', name: 'Enlightened Vault', icon: 'Ability_Paladin_EnlightenedJudgements.PNG', color: 'yellow', rarity: 'rare', cost: 9, legalSlots: [12], active: [{ kind: 'gainMoney', amount: 3 }, { kind: 'gainPoints', amount: 3 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'rose-gold-band', name: 'Rose Gold Band', icon: 'INV_Ring_Bastion_01_PinkGold.PNG', color: 'yellow', rarity: 'common', cost: 3, legalSlots: [1, 5], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'trade', pay: 1, then: [{ kind: 'heal', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'iron-amulet', name: 'Iron Amulet', icon: 'Archaeology_5_0_IronAmulet.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [3, 9], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'lantern-festival', name: 'Lantern Festival', icon: 'Inv_misc_trinket6oIH_lanternA2.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [1, 7], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'rare-hide', name: 'Rare Hide', icon: 'INV_Misc_MonsterScales_01.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [5, 9], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'trade', pay: 2, then: [{ kind: 'gainPoints', amount: 1 }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'final-judgement', name: 'Final Judgement', icon: 'Ability_Paladin_JudgementRed.PNG', color: 'yellow', rarity: 'rare', cost: 8, legalSlots: [7, 12], active: [{ kind: 'gainMoney', amount: 2 }, { kind: 'gainPoints', amount: 2 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  { id: 'amulet-of-plenty', name: 'Amulet of Plenty', icon: 'INV_Jewelry_Amulet_03.PNG', color: 'yellow', rarity: 'common', cost: 5, legalSlots: [3, 11], active: [{ kind: 'gainMoney', amount: 2 }], echo: [{ kind: 'gainPoints', amount: 1 }] },
  { id: 'dawn-lantern', name: 'Dawn Lantern', icon: 'Inv_misc_trinket6oIH_lanternA3.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [1, 12], active: [{ kind: 'gainMoney', amount: 1 }], echo: [{ kind: 'gainMoney', amount: 2 }] },
  // --- 2026-07-14 mechanics batch: gold turns violent. Trades that convert
  // coin stacks into damage and theft are the deliberate 4p coin sink.
  { id: 'hired-blade', name: 'Hired Blade', icon: 'INV_Sword_1H_ArtifactFelomelorn_D_01.PNG', color: 'yellow', rarity: 'common', cost: 5, legalSlots: [5, 7], active: [{ kind: 'trade', pay: 3, then: [{ kind: 'damage', amount: 3, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'bribery', name: 'Bribery', icon: 'INV_Misc_Bag_10.PNG', color: 'yellow', rarity: 'rare', cost: 7, legalSlots: [8], active: [{ kind: 'gainMoney', amount: 1 }, { kind: 'trade', pay: 2, then: [{ kind: 'steal', amount: 2, target: 'chooseOpponent' }] }], echo: [{ kind: 'gainMoney', amount: 1 }] },
  { id: 'loan-shark', name: 'Loan Shark', icon: 'INV_Misc_Landshark.PNG', color: 'yellow', rarity: 'common', cost: 4, legalSlots: [2, 4], active: [{ kind: 'steal', amount: 1, target: 'chooseOpponent' }], echo: [{ kind: 'gainMoney', amount: 1 }] },
];

export function pools() {
  return {
    red: RED_CARDS,
    blue: BLUE_CARDS,
    black: BLACK_CARDS,
    green: GREEN_CARDS,
    yellow: YELLOW_CARDS,
    colorless: COLORLESS_CARDS,
  };
}
